/* teensy_ecat_bridge -- LinuxCNC realtime HAL component for the Teensy EtherCAT
 * master over SPI (spidev).
 *
 * Each servo cycle this component performs one full-duplex SPI transaction with
 * the Teensy (the SPI slave): it sends the immediate outputs + the look-ahead
 * motion stream, and receives the immediate inputs + status. Process-data pins
 * are created dynamically from the generated contract (teensy_bridge_layout.h),
 * so the HAL pin names match the bus XML halPin names exactly.
 *
 * Build/install:
 *   halcompile --install teensy_ecat_bridge.c
 * (teensy_bridge_layout.h must be on the include path; keep it beside this file
 *  or pass -I. The header is regenerated by `make config`.)
 *
 * Load:
 *   loadrt teensy_ecat_bridge device=/dev/spidev0.0 spi_hz=40000000 lead=10
 *   addf teensy-ecat.update servo-thread
 *
 * Transport note: spidev ioctl from the servo thread is a syscall (not strictly
 * hard-RT). The Teensy-side look-ahead buffer absorbs the resulting jitter; if it
 * proves excessive, switch to a direct RP1 SPI register mmap (out of scope here).
 */

#include "rtapi.h"
#include "rtapi_app.h"
#include "hal.h"

#include <stdint.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <linux/spi/spidev.h>

#include "teensy_bridge_layout.h"

MODULE_AUTHOR("RTIC-ECMaster");
MODULE_DESCRIPTION("Teensy EtherCAT master bridge over SPI");
MODULE_LICENSE("GPL");

#define PREFIX "teensy-ecat"

static char *device = "/dev/spidev0.0";
RTAPI_MP_STRING(device, "spidev device path");
static int spi_hz = 40000000;
RTAPI_MP_INT(spi_hz, "SPI clock (Hz)");
static int lead = TEENSY_DEFAULT_LEAD;
RTAPI_MP_INT(lead, "motion look-ahead depth (cycles)");

static int comp_id;
static int spi_fd = -1;

/* Process-data pin storage (one slot used per pin, by type). */
static hal_bit_t **pin_bit;
static hal_s32_t **pin_s32;
static hal_u32_t **pin_u32;

/* Command pins (HAL_IN: set by the rest of the config). */
static hal_bit_t *p_enable, *p_fault_reset, *p_quick_stop;
/* Status pins (HAL_OUT: driven by this component). */
static hal_bit_t *p_link, *p_operational, *p_fault, *p_host_timeout, *p_online;
static hal_s32_t *p_wkc, *p_exp_wkc, *p_buf_depth, *p_crc_errors;
static hal_u32_t *p_cycle_index, *p_phase;

/* Rolling counters / motion stream state. */
static uint16_t seq;
static uint16_t host_wdog;
static uint32_t crc_errors;
static uint32_t next_tag;
static int primed;
static int last_buf_depth;
static uint32_t last_cycle_index;

/* CRC-16/CCITT-FALSE (matches src/hal/host_bridge.rs::crc16). */
static uint16_t crc16(const uint8_t *data, int len)
{
    uint16_t crc = 0xFFFF;
    for (int i = 0; i < len; i++) {
        crc ^= (uint16_t)data[i] << 8;
        for (int b = 0; b < 8; b++)
            crc = (crc & 0x8000) ? (crc << 1) ^ 0x1021 : (crc << 1);
    }
    return crc;
}

static void put_le(uint8_t *buf, int off, uint32_t v, int nbytes)
{
    for (int i = 0; i < nbytes; i++)
        buf[off + i] = (uint8_t)(v >> (8 * i));
}

static uint32_t get_le(const uint8_t *buf, int off, int nbytes)
{
    uint32_t v = 0;
    for (int i = 0; i < nbytes; i++)
        v |= (uint32_t)buf[off + i] << (8 * i);
    return v;
}

/* Serialize one output pin's HAL value into the frame at its byte offset. */
static void serialize_out(uint8_t *frame, const teensy_pin_t *p, int i)
{
    int nbytes = (p->bit_len + 7) / 8;
    if (p->type == 'b') {
        uint8_t mask = (uint8_t)(1u << p->bit_pos);
        if (*pin_bit[i])
            frame[p->frame_off] |= mask;
        else
            frame[p->frame_off] &= (uint8_t)~mask;
    } else if (p->type == 'u') {
        put_le(frame, p->frame_off, (uint32_t)*pin_u32[i], nbytes);
    } else { /* 's' */
        put_le(frame, p->frame_off, (uint32_t)*pin_s32[i], nbytes);
    }
}

/* Scatter one input pin's value out of the frame into its HAL pin. */
static void deserialize_in(const uint8_t *frame, const teensy_pin_t *p, int i)
{
    int nbytes = (p->bit_len + 7) / 8;
    if (p->type == 'b') {
        *pin_bit[i] = (frame[p->frame_off] >> p->bit_pos) & 1;
    } else if (p->type == 'u') {
        *pin_u32[i] = get_le(frame, p->frame_off, nbytes);
    } else { /* 's' sign-extend from bit_len */
        uint32_t raw = get_le(frame, p->frame_off, nbytes);
        int shift = 32 - p->bit_len;
        *pin_s32[i] = (shift > 0 && shift < 32)
                          ? ((int32_t)(raw << shift) >> shift)
                          : (int32_t)raw;
    }
}

/* Build the look-ahead motion stream (B3 flow control). Sends one sample per
 * cycle steady-state; refills extra samples (up to the batch cap) when the
 * Teensy-reported buffer depth has fallen below the target lead. All samples in
 * a refill carry the current setpoint -- LinuxCNC produces one setpoint per
 * servo period, so the lead is a fixed pipeline delay, not future prediction. */
static void build_motion(uint8_t *frame)
{
    if (TEENSY_MOTION_COUNT == 0) {
        frame[TEENSY_STREAM_OFF] = 0;
        return;
    }
    int target = lead > 0 ? lead : 1;
    if (target > TEENSY_MAX_SAMPLES_PER_FRAME && TEENSY_MAX_SAMPLES_PER_FRAME > 0)
        ; /* target may exceed per-frame cap; refill spreads over cycles */

    /* Resync the tag stream to the Teensy's clock if we have fallen behind. */
    if (next_tag < last_cycle_index + 1)
        next_tag = last_cycle_index + 1;

    int want;
    if (!primed) {
        want = target;
        primed = 1;
    } else if (last_buf_depth < target) {
        want = (target - last_buf_depth) + 1;
    } else {
        want = 1;
    }
    if (want > TEENSY_MAX_SAMPLES_PER_FRAME)
        want = TEENSY_MAX_SAMPLES_PER_FRAME;
    if (want < 1)
        want = 1;

    frame[TEENSY_STREAM_OFF] = (uint8_t)want;
    uint8_t *s = frame + TEENSY_STREAM_OFF + 1;
    for (int j = 0; j < want; j++) {
        put_le(s, 0, next_tag++, 4);
        uint8_t *payload = s + 4;
        for (int k = 0; k < TEENSY_MOTION_COUNT; k++) {
            const teensy_motion_t *m = &TEENSY_MOTION[k];
            const teensy_pin_t *p = &TEENSY_PINS[m->pin_index];
            uint32_t v = (p->type == 'u') ? (uint32_t)*pin_u32[m->pin_index]
                                          : (uint32_t)*pin_s32[m->pin_index];
            put_le(payload, m->sample_off, v, m->len);
        }
        s += TEENSY_SAMPLE_STRIDE;
    }
}

static int spi_transfer(const uint8_t *tx, uint8_t *rx, int len)
{
    struct spi_ioc_transfer tr;
    memset(&tr, 0, sizeof(tr));
    tr.tx_buf = (unsigned long)tx;
    tr.rx_buf = (unsigned long)rx;
    tr.len = len;
    tr.speed_hz = spi_hz;
    tr.bits_per_word = 8;
    return ioctl(spi_fd, SPI_IOC_MESSAGE(1), &tr);
}

static void update(void *arg, long period)
{
    (void)arg;
    (void)period;
    static uint8_t mosi[TEENSY_FRAME_LEN];
    static uint8_t miso[TEENSY_FRAME_LEN];

    memset(mosi, 0, sizeof(mosi));
    mosi[0] = (uint8_t)(TEENSY_MAGIC & 0xff);
    mosi[1] = (uint8_t)(TEENSY_MAGIC >> 8);
    mosi[2] = TEENSY_VERSION;
    uint8_t flags = 0;
    if (*p_enable)
        flags |= TEENSY_FLAG_ENABLE;
    if (*p_fault_reset)
        flags |= TEENSY_FLAG_FAULT_RESET;
    if (*p_quick_stop)
        flags |= TEENSY_FLAG_QUICK_STOP;
    mosi[3] = flags;
    seq++;
    put_le(mosi, 4, seq, 2);
    host_wdog++;
    put_le(mosi, 6, host_wdog, 2);

    for (int i = 0; i < TEENSY_PIN_COUNT; i++)
        if (TEENSY_PINS[i].dir == 'o')
            serialize_out(mosi, &TEENSY_PINS[i], i);

    build_motion(mosi);

    uint16_t c = crc16(mosi, TEENSY_MOSI_LEN - 2);
    put_le(mosi, TEENSY_MOSI_LEN - 2, c, 2);

    if (spi_transfer(mosi, miso, TEENSY_FRAME_LEN) < 0) {
        *p_online = 0;
        *p_fault = 1;
        return;
    }

    uint16_t magic = (uint16_t)get_le(miso, 0, 2);
    uint16_t rx_crc = (uint16_t)get_le(miso, TEENSY_MISO_LEN - 2, 2);
    if (magic != TEENSY_MAGIC || crc16(miso, TEENSY_MISO_LEN - 2) != rx_crc) {
        crc_errors++;
        *p_crc_errors = (hal_s32_t)crc_errors;
        *p_online = 0;
        *p_fault = 1;
        return;
    }

    uint8_t status = miso[3];
    *p_online = 1;
    *p_link = (status & TEENSY_ST_LINK) ? 1 : 0;
    *p_operational = (status & TEENSY_ST_OPERATIONAL) ? 1 : 0;
    *p_fault = (status & TEENSY_ST_FAULT) ? 1 : 0;
    *p_host_timeout = (status & TEENSY_ST_HOST_TIMEOUT) ? 1 : 0;
    last_cycle_index = get_le(miso, 8, 4);
    *p_cycle_index = last_cycle_index;
    *p_wkc = miso[12];
    *p_exp_wkc = miso[13];
    *p_phase = miso[14];
    last_buf_depth = miso[16];
    *p_buf_depth = last_buf_depth;
    *p_crc_errors = (hal_s32_t)crc_errors;

    for (int i = 0; i < TEENSY_PIN_COUNT; i++)
        if (TEENSY_PINS[i].dir == 'i')
            deserialize_in(miso, &TEENSY_PINS[i], i);
}

static int make_process_pins(void)
{
    pin_bit = hal_malloc(sizeof(hal_bit_t *) * TEENSY_PIN_COUNT);
    pin_s32 = hal_malloc(sizeof(hal_s32_t *) * TEENSY_PIN_COUNT);
    pin_u32 = hal_malloc(sizeof(hal_u32_t *) * TEENSY_PIN_COUNT);
    if (!pin_bit || !pin_s32 || !pin_u32)
        return -1;

    for (int i = 0; i < TEENSY_PIN_COUNT; i++) {
        const teensy_pin_t *p = &TEENSY_PINS[i];
        hal_pin_dir_t dir = (p->dir == 'o') ? HAL_IN : HAL_OUT;
        int r;
        if (p->type == 'b')
            r = hal_pin_bit_newf(dir, &pin_bit[i], comp_id, "%s.%s", PREFIX, p->name);
        else if (p->type == 'u')
            r = hal_pin_u32_newf(dir, &pin_u32[i], comp_id, "%s.%s", PREFIX, p->name);
        else
            r = hal_pin_s32_newf(dir, &pin_s32[i], comp_id, "%s.%s", PREFIX, p->name);
        if (r < 0)
            return r;
    }
    return 0;
}

static int make_status_pins(void)
{
    int r = 0;
    r |= hal_pin_bit_newf(HAL_IN, &p_enable, comp_id, "%s.enable", PREFIX);
    r |= hal_pin_bit_newf(HAL_IN, &p_fault_reset, comp_id, "%s.fault-reset", PREFIX);
    r |= hal_pin_bit_newf(HAL_IN, &p_quick_stop, comp_id, "%s.quick-stop", PREFIX);
    r |= hal_pin_bit_newf(HAL_OUT, &p_link, comp_id, "%s.link", PREFIX);
    r |= hal_pin_bit_newf(HAL_OUT, &p_operational, comp_id, "%s.operational", PREFIX);
    r |= hal_pin_bit_newf(HAL_OUT, &p_fault, comp_id, "%s.fault", PREFIX);
    r |= hal_pin_bit_newf(HAL_OUT, &p_host_timeout, comp_id, "%s.host-timeout", PREFIX);
    r |= hal_pin_bit_newf(HAL_OUT, &p_online, comp_id, "%s.online", PREFIX);
    r |= hal_pin_s32_newf(HAL_OUT, &p_wkc, comp_id, "%s.wkc", PREFIX);
    r |= hal_pin_s32_newf(HAL_OUT, &p_exp_wkc, comp_id, "%s.expected-wkc", PREFIX);
    r |= hal_pin_s32_newf(HAL_OUT, &p_buf_depth, comp_id, "%s.buffer-depth", PREFIX);
    r |= hal_pin_s32_newf(HAL_OUT, &p_crc_errors, comp_id, "%s.crc-errors", PREFIX);
    r |= hal_pin_u32_newf(HAL_OUT, &p_cycle_index, comp_id, "%s.cycle-index", PREFIX);
    r |= hal_pin_u32_newf(HAL_OUT, &p_phase, comp_id, "%s.phase", PREFIX);
    return r;
}

static int open_spi(void)
{
    spi_fd = open(device, O_RDWR);
    if (spi_fd < 0)
        return -1;
    uint8_t mode = SPI_MODE_0;
    uint8_t bits = 8;
    uint32_t hz = (uint32_t)spi_hz;
    if (ioctl(spi_fd, SPI_IOC_WR_MODE, &mode) < 0 ||
        ioctl(spi_fd, SPI_IOC_WR_BITS_PER_WORD, &bits) < 0 ||
        ioctl(spi_fd, SPI_IOC_WR_MAX_SPEED_HZ, &hz) < 0)
        return -1;
    return 0;
}

int rtapi_app_main(void)
{
    comp_id = hal_init(PREFIX);
    if (comp_id < 0)
        return comp_id;

    if (open_spi() < 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, PREFIX ": cannot open %s\n", device);
        hal_exit(comp_id);
        return -1;
    }
    if (make_process_pins() < 0 || make_status_pins() < 0) {
        rtapi_print_msg(RTAPI_MSG_ERR, PREFIX ": pin export failed\n");
        hal_exit(comp_id);
        return -1;
    }
    if (hal_export_funct(PREFIX ".update", update, NULL, 0, 0, comp_id) < 0) {
        hal_exit(comp_id);
        return -1;
    }
    rtapi_print_msg(RTAPI_MSG_INFO,
                    PREFIX ": ready on %s, frame %d B, %d pins, lead %d\n",
                    device, TEENSY_FRAME_LEN, TEENSY_PIN_COUNT, lead);
    hal_ready(comp_id);
    return 0;
}

void rtapi_app_exit(void)
{
    if (spi_fd >= 0)
        close(spi_fd);
    hal_exit(comp_id);
}
